language: node_js
node_js:
    - "node"

os:
    - linux
    - osx
    - windows

jobs:
    include:
        - stage: Produce Coverage
          node_js: node
          script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

    allow_failures:
        - os: windows
#  deploy:
#     provider: npm
#     email: "flickmor@gmail.com"
#     api_key: "YOUR_AUTH_TOKEN"
