language: node_js
node_js:
    - "node"

os:
    - linux
    - osx
    - windows

jobs:
    allow_failures:
        - os: osx
#  deploy:
#     provider: npm
#     email: "flickmor@gmail.com"
#     api_key: "YOUR_AUTH_TOKEN"
